services:
  - type: web
    name: grammar-scoring-engine
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: PORT
        value: 8501
    healthCheckPath: /
    autoDeploy: true 